// GENERATED by scripts/gen-palette.mjs -- do not edit. Run `npm run gen:palette`.
// Blue steps + neutral + surfaces are from the dataviz reference palette. The RED ARM IS DERIVED
// (same OKLCH lightness as each blue step; hue from the documented categorical red) because
// the reference documents no red ramp. See the header of the generator.
export const PALETTE = {
  "surface": {
    "light": "#fcfcfb",
    "dark": "#1a1a19"
  },
  "neutral": {
    "light": "#f0efec",
    "dark": "#383835"
  },
  "diverging": {
    "light": {
      "neg": [
        "#fac0ba",
        "#ee7e77",
        "#d2383a",
        "#911e22"
      ],
      "mid": "#f0efec",
      "pos": [
        "#b7d3f6",
        "#6da7ec",
        "#2a78d6",
        "#184f95"
      ]
    },
    "dark": {
      "neg": [
        "#882c2f",
        "#b04042",
        "#d5595a",
        "#e38582"
      ],
      "mid": "#383835",
      "pos": [
        "#184f95",
        "#256abf",
        "#3987e5",
        "#6da7ec"
      ]
    }
  },
  "sequential": {
    "light": [
      "#cde2fb",
      "#9ec5f4",
      "#6da7ec",
      "#3987e5",
      "#256abf",
      "#184f95",
      "#0d366b"
    ],
    "dark": [
      "#0d366b",
      "#184f95",
      "#256abf",
      "#3987e5",
      "#6da7ec",
      "#86b6ef"
    ]
  }
} as const;
